#include "SnapLogWiring.hpp"

// Generated by src/slic3r/CMakeLists.txt: SLIC3R_SNAPLOG_ENABLED, SNAP_LOG_HMAC_SECRET.
#include "SnapLogBuildConfig.hpp"

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <future>
#include <memory>
#include <mutex>
#include <random>
#include <utility>
#include <vector>

#include <boost/algorithm/string/predicate.hpp>
#include <boost/filesystem/path.hpp>
#include <boost/log/trivial.hpp>

#include <wx/string.h>
#include <wx/utils.h>

#include "libslic3r_version.h"
#include "libslic3r/AppConfig.hpp"
#include "libslic3r/Utils.hpp"
#include "slic3r/Utils/InstanceID.hpp"
#include "BuildCommit.hpp"
#include "GUI_App.hpp" // PRIVACY_POLICY_FLAGS

namespace Slic3r { namespace GUI { namespace SnapLogWiring {

namespace snap = ::Slic3r::SnapLog::v1;

namespace {

const char* const s_hmac_secret = SNAP_LOG_HMAC_SECRET;

constexpr std::size_t SCRUB_MAX_BYTES = 512;

// State of one guard. The realtime and the batch worker of the client call the guard concurrently.
struct GuardState
{
    std::mutex mutex;
    bool       insecure_put_seen   = false;
    bool       last_create_refused = false;
    bool       bucket_started      = false;
    int        tokens              = 0;
    int64_t    last_refill_ms      = 0;
};

enum class Verdict { Forward, Refuse403, Refuse0 };

// The exact shape of the fakes in the upstream test. http stays null. The future of the promise is
// never taken here: the client takes it once in consume_handle_result(), and a second
// get_future() would throw std::future_error out of its worker thread.
std::shared_ptr<snap::SnapLogHandle> refused(int status)
{
    auto handle  = std::make_shared<snap::SnapLogHandle>();
    handle->prom = std::make_shared<std::promise<snap::SnapLogResult>>();
    handle->prom->set_value({status, std::string{}, /*cancelled*/ false});
    handle->fulfilled.store(true);
    return handle;
}

// The URL without query and fragment.
std::string url_path_part(const std::string& url)
{
    return url.substr(0, url.find_first_of("?#"));
}

int64_t default_steady_ms()
{
    return static_cast<int64_t>(
        std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::steady_clock::now().time_since_epoch()).count());
}

// Token bucket of the create requests; the caller holds state.mutex.
bool take_create_token(GuardState& state, const GuardPolicy& policy, int64_t now_ms)
{
    const int     capacity  = std::max(1, policy.create_burst);
    const int64_t refill_ms = static_cast<int64_t>(std::max(1, policy.create_refill_sec)) * 1000;

    if (!state.bucket_started) {
        state.bucket_started = true;
        state.tokens         = capacity;
        state.last_refill_ms = now_ms;
    } else if (now_ms > state.last_refill_ms) {
        const int64_t earned = (now_ms - state.last_refill_ms) / refill_ms;
        if (earned > 0) {
            if (earned >= static_cast<int64_t>(capacity - state.tokens)) {
                state.tokens         = capacity;
                state.last_refill_ms = now_ms;
            } else {
                state.tokens += static_cast<int>(earned);
                state.last_refill_ms += earned * refill_ms;
            }
        }
    }

    if (state.tokens <= 0)
        return false;
    --state.tokens;
    return true;
}

std::mutex  s_identity_mutex;
bool        s_inited = false;
std::string s_client_id;
std::string s_home_dir;

} // namespace

bool compiled_in()
{
#if SLIC3R_SNAPLOG_ENABLED
    return true;
#else
    return false;
#endif
}

bool has_public_key()
{
    return compiled_in() && s_hmac_secret[0] != '\0';
}

bool effective_consent(const AppConfig& config)
{
    return compiled_in() && config.get_bool(PRIVACY_POLICY_FLAGS) && config.get_bool("snaplog_upload");
}

DoRequest guard_do_request(DoRequest inner, GuardPolicy policy)
{
    auto state = std::make_shared<GuardState>();

    return [inner = std::move(inner), policy = std::move(policy), state](const std::string&                               method,
                                                                         const std::string&                               url,
                                                                         std::vector<std::pair<std::string, std::string>> headers,
                                                                         const boost::filesystem::path*                   body_file,
                                                                         const std::string* body_str) -> std::shared_ptr<snap::SnapLogHandle> {
        Verdict verdict = Verdict::Forward;
        {
            std::lock_guard<std::mutex> lock(state->mutex);

            const bool is_https = boost::algorithm::istarts_with(url, "https://");
            const bool is_signed = std::any_of(headers.begin(), headers.end(), [](const std::pair<std::string, std::string>& header) {
                return boost::algorithm::iequals(header.first, "X-Sign");
            });
            const std::string path = url_path_part(url);

            if (!is_https) {
                // G1. A plain-http PUT target can only come from a create answer; a 403 at the PUT
                // stage does not stop the client, the refused create that follows does.
                if (boost::algorithm::iequals(method, "PUT"))
                    state->insecure_put_seen = true;
                verdict = Verdict::Refuse403;
            } else if (is_signed && !policy.signed_ok) {
                // G2
                verdict = Verdict::Refuse403;
            } else if (boost::algorithm::ends_with(path, "/upload/create")) {
                // G3
                if (state->insecure_put_seen) {
                    verdict = Verdict::Refuse403;
                } else if (take_create_token(*state, policy, policy.steady_ms ? policy.steady_ms() : default_steady_ms())) {
                    state->last_create_refused = false;
                } else {
                    state->last_create_refused = true;
                    verdict                    = Verdict::Refuse0;
                }
            } else if (boost::algorithm::ends_with(path, "/upload/cancel") && state->last_create_refused) {
                // G4: a cancel for a create that never left the process is noise.
                verdict = Verdict::Refuse0;
            }
        }

        if (verdict == Verdict::Refuse403)
            return refused(403);
        if (verdict == Verdict::Refuse0 || !inner)
            return refused(0);
        // G5. The transport may block (name resolution), so the guard state is not locked here.
        return inner(method, url, std::move(headers), body_file, body_str);
    };
}

std::string scrub_text(const std::string& text, const std::string& home_utf8)
{
    std::string result = text.substr(0, text.find('\n'));
    if (!result.empty() && result.back() == '\r')
        result.pop_back();

    // A home directory of one character ("/") would replace every separator.
    if (home_utf8.size() > 1) {
        std::string::size_type pos = 0;
        while ((pos = result.find(home_utf8, pos)) != std::string::npos) {
            result.replace(pos, home_utf8.size(), "~");
            ++pos;
        }
    }

    if (result.size() > SCRUB_MAX_BYTES) {
        std::size_t cut = SCRUB_MAX_BYTES;
        // Never cut inside a multi-byte character: step back over continuation bytes (10xxxxxx).
        while (cut > 0 && (static_cast<unsigned char>(result[cut]) & 0xC0) == 0x80)
            --cut;
        result.resize(cut);
    }
    return result;
}

void init(AppConfig& config)
{
    if (!compiled_in())
        return;

    {
        std::lock_guard<std::mutex> lock(s_identity_mutex);
        if (s_inited)
            return;
        s_inited = true;
    }

    // The block of Snapmaker upstream 2d1554e660 (GUI_App::on_init_inner), with the fork's
    // differences marked.
    snap::SnapLogConfig snap_cfg;
    const std::string   country_code = config.get_country_code();
    snap_cfg.gateway_base = (country_code.find("CN") != std::string::npos) ? "https://api.snapmaker.cn" : "https://api.snapmaker.com";
    snap_cfg.hmac_secret  = s_hmac_secret;
    snap_cfg.spool_dir    = (boost::filesystem::path(data_dir()) / "log_upload_spool").string();

    const std::string machine_id = ::Slic3r::instance_id::ensure(config);
    // Fork: the home directory, not data_dir(), is what has to disappear from paths.
    const std::string home_dir = wxGetHomeDir().utf8_string();
    {
        std::lock_guard<std::mutex> lock(s_identity_mutex);
        s_client_id = machine_id;
        s_home_dir  = home_dir;
    }

    snap_cfg.app_version = SLIC3R_BUILD_ID;
    // Fork: the commit hash is not a global macro here.
    snap_cfg.app_build = build_commit_hash;
#if defined(_WIN32)
    snap_cfg.platform = "Windows";
#elif defined(__APPLE__)
    snap_cfg.platform = "macOS";
#elif defined(__linux__)
    snap_cfg.platform = "Linux";
#else
    snap_cfg.platform = "Unknown";
#endif
    snap_cfg.os_version = wxGetOsDescription().utf8_string();
    {
        std::random_device                          rd;
        std::uniform_int_distribution<unsigned int> dist(0, 255);
        char                                        hex[33];
        for (int i = 0; i < 16; ++i)
            std::snprintf(hex + i * 2, 3, "%02x", dist(rd));
        snap_cfg.session_id.assign(hex, 32);
    }
    snap_cfg.process_id      = std::to_string(get_current_pid());
    snap_cfg.region          = country_code;
    snap_cfg.home_for_redact = home_dir;
    // Fork: upstream polls every 50 ms. The tick is also the retry cadence of the batch channel.
    snap_cfg.poll_interval_ms = 250;

    snap::SnapLogDeps deps;
    // Fork: a value, never the AppConfig itself, which ~GUI_App deletes while a late worker may
    // still hold this closure. Later changes arrive through apply_consent().
    const bool consent = effective_consent(config);
    deps.consent_ok    = [consent]() { return consent; };
    deps.machine_id    = [machine_id]() -> std::string { return machine_id; };
    deps.now_ms        = []() -> int64_t {
        return static_cast<int64_t>(
            std::chrono::duration_cast<std::chrono::milliseconds>(std::chrono::system_clock::now().time_since_epoch()).count());
    };
    // Fork: the transport is built from the complete configuration and wrapped by the guard.
    GuardPolicy policy;
    policy.signed_ok = has_public_key();
    deps.do_request  = guard_do_request(snap::make_production_do_request(snap_cfg), std::move(policy));

    snap::SnapLogClient::instance().init(std::move(deps), std::move(snap_cfg));
    BOOST_LOG_TRIVIAL(info) << "SnapLogClient initialized, consent " << (consent ? "on" : "off") << ", public key "
                            << (has_public_key() ? "present" : "absent");
}

void apply_consent(const AppConfig& config)
{
    if (!compiled_in())
        return;
    // A no-op of the client before init() and after shutdown().
    snap::SnapLogClient::instance().set_consent(effective_consent(config));
}

void mirror_device_id(const std::string& dev_id)
{
    if (!compiled_in())
        return;
    std::string client_id;
    {
        std::lock_guard<std::mutex> lock(s_identity_mutex);
        client_id = s_client_id;
    }
    snap::SnapLogClient::instance().set_device_id(dev_id.empty() ? std::string() : snap::hash_pii(client_id, dev_id));
}

std::string scrub_reason(const std::string& reason)
{
    std::string home_dir;
    {
        std::lock_guard<std::mutex> lock(s_identity_mutex);
        home_dir = s_home_dir;
    }
    return scrub_text(reason, home_dir);
}

void shutdown()
{
    if (!compiled_in())
        return;
    // A no-op of the client when it was never initialised or is already down.
    snap::SnapLogClient::instance().shutdown();
}

}}} // namespace Slic3r::GUI::SnapLogWiring
